version: "3"
services:
  angular-material-frontend-boilerplate:
    container_name: angular-material-frontend-boilerplate
    build: .
    restart: always
    labels:
      - "traefik.enabled=true"
      - "traefik.backend=angular-material-frontend-boilerplate"
      - "traefik.frontend.rule=Host:ADD_HOST_HERE"
      - "traefik.port=80"
    networks:
      - "web"
networks:
  web:
    external:
      name: web